### ISSUE TITLE
xml dont show preview

### ISSUE THREAD

**Issue by drvafa** [shiburagi/Drawer-Behavior#17]
when added into my xml,  show below error

`java.lang.NullPointerException
	at com.infideap.drawerbehavior.AdvanceDrawerLayout.init(AdvanceDrawerLayout.java:75)
	at com.infideap.drawerbehavior.AdvanceDrawerLayout.<init>(AdvanceDrawerLayout.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:403)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:186)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:144)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:309)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:418)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:429)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:333)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:326)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:391)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:195)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:540)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$5(RenderTask.java:666)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

![Screenshot from 2019-06-26 21-52-38](https://user-images.githubusercontent.com/16055760/60201175-f23ce100-985c-11e9-8902-ad42c5d756aa.png)

**Comment by shiburagi** [comment]
i will check it. tq

**Comment by shiburagi** [comment]
@drvafa can u try using this version,

`implementation 'com.infideap.drawerbehavior:drawer-behavior:0.2.1'`
