### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Cannot set 'scaleY' to Float.NaN

### ISSUE THREAD

**Issue by superdiazzz** [shiburagi/Drawer-Behavior#36]
I got crash in some user which crashlytics said:

```
Fatal Exception: java.lang.IllegalArgumentException: Cannot set 'scaleY' to Float.NaN
       at android.view.View.sanitizeFloatPropertyValue(View.java:17723)
       at android.view.View.sanitizeFloatPropertyValue(View.java:17697)
       at android.view.View.setScaleY(View.java:17091)
       at androidx.core.view.ViewCompat.setScaleY(ViewCompat.java)
       at com.infideap.drawerbehavior.AdvanceDrawerLayout.updateSlideOffset(AdvanceDrawerLayout.java:361)
       at com.infideap.drawerbehavior.AdvanceDrawerLayout.access$updateSlideOffset(AdvanceDrawerLayout.java)
       at com.infideap.drawerbehavior.AdvanceDrawerLayout$init$1.onDrawerSlide(AdvanceDrawerLayout.java:12)
       at androidx.drawerlayout.widget.DrawerLayout.dispatchOnDrawerSlide(DrawerLayout.java:20)
       at androidx.drawerlayout.widget.DrawerLayout.setDrawerViewOffset(DrawerLayout.java:15)
       at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:177)
       at android.view.View.layout(View.java:23266)
       at android.view.ViewGroup.layout(ViewGroup.java:6532)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23266)
       at android.view.ViewGroup.layout(ViewGroup.java:6532)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23266)
       at android.view.ViewGroup.layout(ViewGroup.java:6532)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23266)
       at android.view.ViewGroup.layout(ViewGroup.java:6532)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:23266)
       at android.view.ViewGroup.layout(ViewGroup.java:6532)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:804)
       at android.view.View.layout(View.java:23266)
       at android.view.ViewGroup.layout(ViewGroup.java:6532)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3708)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3166)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2135)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8624)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
       at android.view.Choreographer.doCallbacks(Choreographer.java:799)
       at android.view.Choreographer.doFrame(Choreographer.java:734)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```
I use this dependency
`implementation 'com.infideap.drawerbehavior:drawer-behavior:1.0.4'`

and crash occurs
![Screen Shot 2022-11-09 at 12 01 36](https://user-images.githubusercontent.com/10770867/200742891-2f22c8a5-63f2-4739-adb2-12d4290e36fd.png)

However i can't produce the crash, i don't know how this could happened. Please help

**Comment by nicemak** [comment]
Any solution?

**Comment by nicemak** [comment]
> I got crash in some user which crashlytics said:
> 
> ```
> Fatal Exception: java.lang.IllegalArgumentException: Cannot set 'scaleY' to Float.NaN
>        at android.view.View.sanitizeFloatPropertyValue(View.java:17723)
>        at android.view.View.sanitizeFloatPropertyValue(View.java:17697)
>        at android.view.View.setScaleY(View.java:17091)
>        at androidx.core.view.ViewCompat.setScaleY(ViewCompat.java)
>        at com.infideap.drawerbehavior.AdvanceDrawerLayout.updateSlideOffset(AdvanceDrawerLayout.java:361)
>        at com.infideap.drawerbehavior.AdvanceDrawerLayout.access$updateSlideOffset(AdvanceDrawerLayout.java)
>        at com.infideap.drawerbehavior.AdvanceDrawerLayout$init$1.onDrawerSlide(AdvanceDrawerLayout.java:12)
>        at androidx.drawerlayout.widget.DrawerLayout.dispatchOnDrawerSlide(DrawerLayout.java:20)
>        at androidx.drawerlayout.widget.DrawerLayout.setDrawerViewOffset(DrawerLayout.java:15)
>        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:177)
>        at android.view.View.layout(View.java:23266)
>        at android.view.ViewGroup.layout(ViewGroup.java:6532)
>        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
>        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
>        at android.view.View.layout(View.java:23266)
>        at android.view.ViewGroup.layout(ViewGroup.java:6532)
>        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
>        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
>        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
>        at android.view.View.layout(View.java:23266)
>        at android.view.ViewGroup.layout(ViewGroup.java:6532)
>        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
>        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
>        at android.view.View.layout(View.java:23266)
>        at android.view.ViewGroup.layout(ViewGroup.java:6532)
>        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
>        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
>        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
>        at android.view.View.layout(View.java:23266)
>        at android.view.ViewGroup.layout(ViewGroup.java:6532)
>        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
>        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
>        at com.android.internal.policy.DecorView.onLayout(DecorView.java:804)
>        at android.view.View.layout(View.java:23266)
>        at android.view.ViewGroup.layout(ViewGroup.java:6532)
>        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3708)
>        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3166)
>        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2135)
>        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8624)
>        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
>        at android.view.Choreographer.doCallbacks(Choreographer.java:799)
>        at android.view.Choreographer.doFrame(Choreographer.java:734)
>        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
>        at android.os.Handler.handleCallback(Handler.java:938)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loop(Looper.java:236)
>        at android.app.ActivityThread.main(ActivityThread.java:8057)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
> ```
> 
> I use this dependency `implementation 'com.infideap.drawerbehavior:drawer-behavior:1.0.4'`
> 
> and crash occurs ![Screen Shot 2022-11-09 at 12 01 36](https://user-images.githubusercontent.com/10770867/200742891-2f22c8a5-63f2-4739-adb2-12d4290e36fd.png)
> 
> However i can't produce the crash, i don't know how this could happened. Please help

did you find anything?

**Comment by Sikandar106** [comment]
kindly check your navigation view visibility inside your drawer xml if its visibility gone make it visible so you can fix this problem
